// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: api/room/v1/room.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRoomServiceCreateRoom = "/room.v1.RoomService/CreateRoom"
const OperationRoomServiceDeleteRoom = "/room.v1.RoomService/DeleteRoom"
const OperationRoomServiceGetMessages = "/room.v1.RoomService/GetMessages"
const OperationRoomServiceGetRoom = "/room.v1.RoomService/GetRoom"
const OperationRoomServiceIsMember = "/room.v1.RoomService/IsMember"
const OperationRoomServiceJoinRoom = "/room.v1.RoomService/JoinRoom"
const OperationRoomServiceLeaveRoom = "/room.v1.RoomService/LeaveRoom"
const OperationRoomServiceListRoomMembers = "/room.v1.RoomService/ListRoomMembers"
const OperationRoomServiceListRooms = "/room.v1.RoomService/ListRooms"

type RoomServiceHTTPServer interface {
	// CreateRoom创建房间
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomReply, error)
	// DeleteRoom 删除房间（只有房主可以删除）
	DeleteRoom(context.Context, *DeleteRoomRequest) (*emptypb.Empty, error)
	// GetMessages查询指定房间的消息列表
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesReply, error)
	// GetRoom根据 ID 查询单个房间
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	// IsMember 检查是否为房间成员
	IsMember(context.Context, *IsMemberRequest) (*IsMemberReply, error)
	// JoinRoom 加入房间
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomReply, error)
	// LeaveRoom 离开房间
	LeaveRoom(context.Context, *LeaveRoomRequest) (*emptypb.Empty, error)
	// ListRoomMembers 查询房间成员列表
	ListRoomMembers(context.Context, *ListRoomMembersRequest) (*ListRoomMembersReply, error)
	// ListRooms列出房间（可按用户 ID 过滤）
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsReply, error)
}

func RegisterRoomServiceHTTPServer(s *http.Server, srv RoomServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/rooms", _RoomService_CreateRoom0_HTTP_Handler(srv))
	r.DELETE("/v1/rooms/{id}", _RoomService_DeleteRoom0_HTTP_Handler(srv))
	r.POST("/v1/rooms/{room_id}/join", _RoomService_JoinRoom0_HTTP_Handler(srv))
	r.POST("/v1/rooms/{room_id}/leave", _RoomService_LeaveRoom0_HTTP_Handler(srv))
	r.GET("/v1/rooms/{id}", _RoomService_GetRoom0_HTTP_Handler(srv))
	r.GET("/v1/rooms", _RoomService_ListRooms0_HTTP_Handler(srv))
	r.GET("/v1/rooms/{room_id}/messages", _RoomService_GetMessages0_HTTP_Handler(srv))
	r.GET("/v1/rooms/{room_id}/members", _RoomService_ListRoomMembers0_HTTP_Handler(srv))
	r.GET("/v1/rooms/{room_id}/is-member", _RoomService_IsMember0_HTTP_Handler(srv))
}

func _RoomService_CreateRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceCreateRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRoom(ctx, req.(*CreateRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRoomReply)
		return ctx.Result(200, reply)
	}
}

func _RoomService_DeleteRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceDeleteRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRoom(ctx, req.(*DeleteRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _RoomService_JoinRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceJoinRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JoinRoom(ctx, req.(*JoinRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JoinRoomReply)
		return ctx.Result(200, reply)
	}
}

func _RoomService_LeaveRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LeaveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceLeaveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LeaveRoom(ctx, req.(*LeaveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _RoomService_GetRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceGetRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoom(ctx, req.(*GetRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Room)
		return ctx.Result(200, reply)
	}
}

func _RoomService_ListRooms0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceListRooms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRooms(ctx, req.(*ListRoomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomsReply)
		return ctx.Result(200, reply)
	}
}

func _RoomService_GetMessages0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceGetMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMessages(ctx, req.(*GetMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMessagesReply)
		return ctx.Result(200, reply)
	}
}

func _RoomService_ListRoomMembers0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoomMembersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceListRoomMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoomMembers(ctx, req.(*ListRoomMembersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomMembersReply)
		return ctx.Result(200, reply)
	}
}

func _RoomService_IsMember0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IsMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceIsMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IsMember(ctx, req.(*IsMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IsMemberReply)
		return ctx.Result(200, reply)
	}
}

type RoomServiceHTTPClient interface {
	// CreateRoom创建房间
	CreateRoom(ctx context.Context, req *CreateRoomRequest, opts ...http.CallOption) (rsp *CreateRoomReply, err error)
	// DeleteRoom 删除房间（只有房主可以删除）
	DeleteRoom(ctx context.Context, req *DeleteRoomRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetMessages查询指定房间的消息列表
	GetMessages(ctx context.Context, req *GetMessagesRequest, opts ...http.CallOption) (rsp *GetMessagesReply, err error)
	// GetRoom根据 ID 查询单个房间
	GetRoom(ctx context.Context, req *GetRoomRequest, opts ...http.CallOption) (rsp *Room, err error)
	// IsMember 检查是否为房间成员
	IsMember(ctx context.Context, req *IsMemberRequest, opts ...http.CallOption) (rsp *IsMemberReply, err error)
	// JoinRoom 加入房间
	JoinRoom(ctx context.Context, req *JoinRoomRequest, opts ...http.CallOption) (rsp *JoinRoomReply, err error)
	// LeaveRoom 离开房间
	LeaveRoom(ctx context.Context, req *LeaveRoomRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ListRoomMembers 查询房间成员列表
	ListRoomMembers(ctx context.Context, req *ListRoomMembersRequest, opts ...http.CallOption) (rsp *ListRoomMembersReply, err error)
	// ListRooms列出房间（可按用户 ID 过滤）
	ListRooms(ctx context.Context, req *ListRoomsRequest, opts ...http.CallOption) (rsp *ListRoomsReply, err error)
}

type RoomServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRoomServiceHTTPClient(client *http.Client) RoomServiceHTTPClient {
	return &RoomServiceHTTPClientImpl{client}
}

// CreateRoom创建房间
func (c *RoomServiceHTTPClientImpl) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...http.CallOption) (*CreateRoomReply, error) {
	var out CreateRoomReply
	pattern := "/v1/rooms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceCreateRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteRoom 删除房间（只有房主可以删除）
func (c *RoomServiceHTTPClientImpl) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/rooms/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceDeleteRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMessages查询指定房间的消息列表
func (c *RoomServiceHTTPClientImpl) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...http.CallOption) (*GetMessagesReply, error) {
	var out GetMessagesReply
	pattern := "/v1/rooms/{room_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceGetMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoom根据 ID 查询单个房间
func (c *RoomServiceHTTPClientImpl) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...http.CallOption) (*Room, error) {
	var out Room
	pattern := "/v1/rooms/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceGetRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// IsMember 检查是否为房间成员
func (c *RoomServiceHTTPClientImpl) IsMember(ctx context.Context, in *IsMemberRequest, opts ...http.CallOption) (*IsMemberReply, error) {
	var out IsMemberReply
	pattern := "/v1/rooms/{room_id}/is-member"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceIsMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// JoinRoom 加入房间
func (c *RoomServiceHTTPClientImpl) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...http.CallOption) (*JoinRoomReply, error) {
	var out JoinRoomReply
	pattern := "/v1/rooms/{room_id}/join"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceJoinRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LeaveRoom 离开房间
func (c *RoomServiceHTTPClientImpl) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/rooms/{room_id}/leave"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceLeaveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoomMembers 查询房间成员列表
func (c *RoomServiceHTTPClientImpl) ListRoomMembers(ctx context.Context, in *ListRoomMembersRequest, opts ...http.CallOption) (*ListRoomMembersReply, error) {
	var out ListRoomMembersReply
	pattern := "/v1/rooms/{room_id}/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceListRoomMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRooms列出房间（可按用户 ID 过滤）
func (c *RoomServiceHTTPClientImpl) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...http.CallOption) (*ListRoomsReply, error) {
	var out ListRoomsReply
	pattern := "/v1/rooms"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceListRooms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
